### ISSUE TITLE
Error compiling C++

### ISSUE THREAD

**Issue by seanbarclay** [WhoLsJohnGalt/watson-unreal-sdk-plugin#5]
Tried compiling the C++ actor on OS X UE 4.17 and got the following error: 

Running Mono...

Setting up Mono
/Users/Shared/Epic Games/UE_4.17/Engine /Users/Shared/Epic Games/UE_4.17/Engine/Binaries/Mac
Compiling game modules for hot reload
Parsing headers for VoiceTestCPPEditor
  Running UnrealHeaderTool "/Users/seanbarclay/Documents/Unreal Projects/VoiceTestCPP/VoiceTestCPP.uproject" "/Users/seanbarclay/Documents/Unreal Projects/VoiceTestCPP/Intermediate/Build/Mac/VoiceTestCPPEditor/Development/VoiceTestCPPEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
/Users/seanbarclay/Documents/Unreal Projects/VoiceTestCPP/Source/VoiceTestCPP/MyActor.h(23)  : **Error: Unrecognized type 'USpeaker' - type must be a UCLASS, USTRUCT or UENUM
Error: UnrealHeaderTool failed for target 'VoiceTestCPPEditor' (platform: Mac, module info: /Users/seanbarclay/Documents/Unreal** **Projects/VoiceTestCPP/Intermediate/Build/Mac/VoiceTestCPPEditor/Development/VoiceTestCPPEditor.uhtmanifest, exit code: OtherCompilationError (5)).**

**Comment by TerryTsai** [comment]
Hey Sean! Sorry, I think you may have gotten an older version of the plugin. I've updated the README with instructions and have tested on Windows and OSX. I will also send you a link to a sample project as soon as I get a chance. Currently still in training.

**Comment by seanbarclay** [comment]
@TerryTsai thanks for the update. Just tested the latest build. 

I saw the following error with the new build on OS X:
---- START ----


Running Mono...

Setting up Mono
/Users/Shared/Epic Games/UE_4.17/Engine /Users/Shared/Epic Games/UE_4.17/Engine/Binaries/Mac
Compiling game modules for hot reload
Parsing headers for TestCPP2Editor
  Running UnrealHeaderTool "/Users/seanbarclay/Documents/Unreal Projects/TestCPP2/TestCPP2.uproject" "/Users/seanbarclay/Documents/Unreal Projects/TestCPP2/Intermediate/Build/Mac/TestCPP2Editor/Development/TestCPP2Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
Reflection code generated for TestCPP2Editor in 13.6654574 seconds
Performing 4 actions (8 in parallel)
[2/4] Compile MyActor.cpp
[1/4] Compile MyActor.gen.cpp
[3/4] Compile TestCPP2.init.gen.cpp
In file included from /Users/seanbarclay/Documents/Unreal Projects/TestCPP2/Intermediate/Build/Mac/UE4Editor/Inc/TestCPP2/MyActor.gen.cpp:8:
In file included from ../../../../../seanbarclay/Documents/Unreal Projects/TestCPP2/Source/TestCPP2/MyActor.h:4:
In file included from ../Plugins/watson-unreal-sdk-plugin/Source/WatsonSdk/Public/Watson.h:4:
../Plugins/watson-unreal-sdk-plugin/Source/WatsonSdk/Public/Common/Authentication.h:4:10: fatal error: 'Authentication.generated.h' file not found
#include "Authentication.generated.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from /Users/seanbarclay/Documents/Unreal Projects/TestCPP2/Source/TestCPP2/MyActor.cpp:4:
In file included from ../../../../../seanbarclay/Documents/Unreal Projects/TestCPP2/Source/TestCPP2/MyActor.h:4:
In file included from ../Plugins/watson-unreal-sdk-plugin/Source/WatsonSdk/Public/Watson.h:4:
../Plugins/watson-unreal-sdk-plugin/Source/WatsonSdk/Public/Common/Authentication.h:4:10: fatal error: 'Authentication.generated.h' file not found
#include "Authentication.generated.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ERROR: UBT ERROR: Failed to produce item: /Users/seanbarclay/Documents/Unreal Projects/TestCPP2/Binaries/Mac/UE4Editor-TestCPP2-4375.dylib
Total build time: 33.22 seconds (Local executor: 0.00 seconds)

---- END ----

**Comment by seanbarclay** [comment]
Also, I got an error saying that the module was looking for "WatsonSDK".

I modified this:

PrivateDependencyModuleNames.AddRange(new string[] {
    "WatsonSDK",
    "Voice"
  });

to this:

PrivateDependencyModuleNames.AddRange(new string[] {
    "**WatsonSdk**",
    "Voice"
  });

I was then able to compile till I saw the error above. Hope this helps and thanks for cranking on this.

**Comment by seanbarclay** [comment]
seeing this when working with 4.18


Running Mono...

Setting up Mono
/Users/Shared/Epic Games/UE_4.18/Engine /Users/Shared/Epic Games/UE_4.18/Engine/Binaries/Mac
Compiling game modules for hot reload
ERROR: Expecting to find a type to be declared in a module rules named 'WatsonSDK' in UE4Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.

**Comment by seanbarclay** [comment]
steps to repeat:

1. created a C++ project w/ 4.18
2. set to `Blank` + `No starter content`
3. in content area > `add new` > `New C++ Class`. Set to `Actor`
4. compiled the project then quit.
5. pulled GH repo to this directory `/Users/Shared/Epic Games/UE_4.18/Engine/Plugins/watson-unreal-sdk-plugin`
6. replaced MyActor.h and MyActor.cpp located in the project `/Users/seanbarclay/Documents/Unreal Projects/MyProject/Source/MyProject/` with your code in the GH README.MD
7. Ran `MyProject.uproject`
8. Hit `Compile` in the UE Project UI
9. Error message will display in bottom right corner.

**Comment by TerryTsai** [comment]
Hey Sean, I apologize for all these issues you're running into. I'm updating my unreal version and testing a fresh project now.

**Comment by seanbarclay** [comment]
Thanks @TerryTsai!

**Comment by seanbarclay** [comment]
@TerryTsai @WhoLsJohnGalt I resolved some issues with WatsonSdk vs. WatsonSDK. Now, I'm getting the following error, which appears to be related to authentication:

Running Mono...

Setting up Mono
/Users/Shared/Epic Games/UE_4.18/Engine /Users/Shared/Epic Games/UE_4.18/Engine/Binaries/Mac
Compiling game modules for hot reload
Performing 3 actions (8 in parallel)
[2/3] Compile MyActor.cpp
[1/3] Compile MyActor.gen.cpp
In file included from /Users/seanbarclay/Documents/Unreal Projects/MyProject5/Intermediate/Build/Mac/UE4Editor/Inc/MyProject5/MyActor.gen.cpp:8:
In file included from ../../../../../seanbarclay/Documents/Unreal Projects/MyProject5/Source/MyProject5/MyActor.h:4:
In file included from ../Plugins/watson-unreal-sdk-plugin/Source/WatsonSDK/Public/Watson.h:4:
../Plugins/watson-unreal-sdk-plugin/Source/WatsonSDK/Public/Common/Authentication.h:4:10: fatal error: 'Authentication.generated.h' file not found
#include "Authentication.generated.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from /Users/seanbarclay/Documents/Unreal Projects/MyProject5/Source/MyProject5/MyActor.cpp:4:
In file included from ../../../../../seanbarclay/Documents/Unreal Projects/MyProject5/Source/MyProject5/MyActor.h:4:
In file included from ../Plugins/watson-unreal-sdk-plugin/Source/WatsonSDK/Public/Watson.h:4:
../Plugins/watson-unreal-sdk-plugin/Source/WatsonSDK/Public/Common/Authentication.h:4:10: fatal error: 'Authentication.generated.h' file not found
#include "Authentication.generated.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ERROR: UBT ERROR: Failed to produce item: /Users/seanbarclay/Documents/Unreal Projects/MyProject5/Binaries/Mac/UE4Editor-MyProject5-5729.dylib
Total build time: 20.35 seconds (Local executor: 0.00 seconds)

**Comment by TerryTsai** [comment]
Hey Sean,
I tested a fresh project on both osx and windows, but was not having any issues. I've been putting it in the project specific Plugins folder: /Users/seanbarclay/Documents/Unreal Projects/MyProject5/Plugins/watson-unreal-sdk-plugin. Is that where you have it as well?

**Comment by seanbarclay** [comment]
Thanks @TerryTsai. I'm getting build errors now. 
@WhoLsJohnGalt can you test and see if there's a step that I'm missing? Thanks!

**Comment by WhoLsJohnGalt** [comment]
Hey @TerryTsai & @seanbarclay I'm having the same issue here.

@TerryTsai maybe in tomorrow's meeting you walk us through how you set it up? Seems we're missing something.

**Comment by TerryTsai** [comment]
That sounds good. I think the issue might actually be from copying my MyActor.h sample header. I think the step I neglected to mention was that in the class definition, you'll want to replace the WATSONSDKTESTBED_API macro with your project specific macro. It should just be your project name in all caps (MYPROJECT5_API). I'm guessing that's what is preventing the UHT tool from auto-generating those files.

**Comment by WhoLsJohnGalt** [comment]
Closing. Error occurred due to project name not being replaced. Instructions have been updated.
